position = "left_player";
x_surface = global.camera_x_offset;
y_surface = 930;
portal_x = 346; // 410 or 346
portal_y = 316; // 375 or 316
board_scale = 0.8439; // 1.02 or 0.8439
max_channel = 0;
max_channel_ind = 0;
tied = false;

surface = -1;
radius_1 = 0;
radius_2 = 0;
radius_3 = 0;
radius_4 = 0;
radius_5 = 0;
radius_6 = 0;
radius_7 = 0;
radius_8 = 0;
portal_seq_1 = noone;
portal_seq_2 = noone;
portal_seq_3 = noone;
portal_seq_4 = noone;
portal_seq_5 = noone;
portal_seq_6 = noone;
portal_seq_7 = noone;
portal_seq_8 = noone;
portal_in_progress = false;
portal_done_1 = false;
portal_done_2 = false;
portal_done_3 = false;
portal_done_4 = false;
portal_done_5 = false;
portal_done_6 = false;
portal_done_7 = false;
portal_done_8 = false;

//rock_click = noone;
//summit_flare = noone;
//summit_emitter = false;
//summit_clicks = 0;
//volcano_clicks = 0;
//volcano_smoke = noone;
//volcano_erupt = noone;

//ice_click = noone;
//blueflames = [];
//outpost_clicks = 0;
//outpost_bubble = noone;
//shield_seq = noone;

//onyx_lefts = [];
//onyx_middles = [];
//onyx_rights = [];

ruby_clicks = []
pearl_clicks = []
onyx_clicks = []
sapphire_clicks = []
emerald_clicks = []
citrine_clicks = []
opal_clicks = []
amethyst_clicks = []